# Generated by Django 5.0.6 on 2024-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_classroom_name_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
