# Generated by Django 5.0.6 on 2024-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
